### ISSUE TITLE
配置项修改

### ISSUE THREAD

**Issue by Galen-Yip** [wertycn/hexo-deployer-qcloud-cos#2]
cosSecretId，cosSecretKey 这两项建议修改成 secretId、secretKey 。因为是腾讯云通用的密钥，不是cos特有的

**Comment by wertycn** [comment]
过了这么久才回复，实在是太懒了，不过还是有必要解释下，对于当前项目，仅是用于将资源上传到cos ，按照云服务安全的最佳实践--最小权限原则 ，程序应该只能访问当下所必需的信息或者资源， 在使用本插件时，应该提供只具有cos权限的密钥，因此命名以cos开头是刻意设定的，在使用文档中也专门提供了独立权限密钥的创建方法
